name: pre-steps
runs:
  using: composite
  steps:
  - name: Free Disk Space
    run: |-
      rm -rf /usr/local/lib/android
      rm -rf /usr/share/dotnet
      rm -rf /opt/ghc
      apt-get remove -y 'php.*'
    shell: bash
  - name: Clone rocksdb
    run: |
      git clone --depth 1 https://github.com/facebook/rocksdb.git
    shell: bash
  - uses: actions/checkout@v4
    with:
      # Relative path under $GITHUB_WORKSPACE to place the repository
      path: rocksdb/plugin/encfs
  - name: Setup Environment Variables
    run: |-
      echo "ROCKSDB_PLUGINS=encfs" >> $GITHUB_ENV
      echo "CIRCLECI=1" >> $GITHUB_ENV
      echo "GTEST_THROW_ON_FAILURE=0" >> $GITHUB_ENV
      echo "GTEST_OUTPUT=xml:/tmp/test-results/" >> $GITHUB_ENV
      echo "SKIP_FORMAT_BUCK_CHECKS=1" >> $GITHUB_ENV
      echo "GTEST_COLOR=1" >> $GITHUB_ENV
      echo "CTEST_OUTPUT_ON_FAILURE=1" >> $GITHUB_ENV
      echo "CTEST_TEST_TIMEOUT=300" >> $GITHUB_ENV
      echo "ZLIB_DOWNLOAD_BASE=https://rocksdb-deps.s3.us-west-2.amazonaws.com/pkgs/zlib" >> $GITHUB_ENV
      echo "BZIP2_DOWNLOAD_BASE=https://rocksdb-deps.s3.us-west-2.amazonaws.com/pkgs/bzip2" >> $GITHUB_ENV
      echo "SNAPPY_DOWNLOAD_BASE=https://rocksdb-deps.s3.us-west-2.amazonaws.com/pkgs/snappy" >> $GITHUB_ENV
      echo "LZ4_DOWNLOAD_BASE=https://rocksdb-deps.s3.us-west-2.amazonaws.com/pkgs/lz4" >> $GITHUB_ENV
      echo "ZSTD_DOWNLOAD_BASE=https://rocksdb-deps.s3.us-west-2.amazonaws.com/pkgs/zstd" >> $GITHUB_ENV
    shell: bash
